#ifndef ERRORS_H__
#define ERRORS_H__

#define OK 0
#define ERROR_ARGC 1
#define ERROR_INVALID_ACTION 2
#define ERROR_IO_FILE 3
#define ERROR_INVALID_SIZE 4
#define ERROR_MEMORY 5
#define ERRROR_INVALID_EL 6
#define ERROR_INVALID_RANGE 7
#define ERROR_RANGE_SUM 8
#define ERROR_RANGE_MULT 9
#define ERROR_DEGENERATE_MATRIX 10
#define ERROR_INVALID_EL_VECTOR 11
#define ERROR_EMPTY_PTR 12
#define ERROR_RANGE_GAUS 13
#define ERROR_INAVLID_MAX_ROW 14

#endif
